In [1]:
st = 'this is a string'

In [2]:
print('hello world')

hello world


In [3]:
print(st[10:16])

string


In [4]:
display(st)

'this is a string'

In [6]:
display(st[10:16])

'string'

In [7]:
hw = 'hello world'

In [8]:
print(hw + ", " + st)

hello world, this is a string


In [9]:
print("this" in st)

True


In [10]:
print(hw * 3)

hello worldhello worldhello world


In [11]:
print(type(st))

<class 'str'>


In [12]:
name = 'Pranav'
level = 23

In [15]:
print(f"my name is {name}, I'm {level} years old")

my name is Pranav, I'm 23 years old


In [16]:
print("my name is %s and I'm %s years old" %(name, level))
print("my name is {} and I'm {} years old".format(name, level))

my name is Pranav and I'm 23 years old
my name is Pranav and I'm 23 years old


In [17]:
(2+4)*(5/3)

10.0

In [18]:
my_list = [1,2,3,4,5]

In [19]:
my_list

[1, 2, 3, 4, 5]

In [21]:
my_list[3]

4

In [22]:
len(my_list)

5

In [23]:
my_list = [1,2.4,'Pranav']

In [24]:
my_list

[1, 2.4, 'Pranav']

In [25]:
l=my_list

In [26]:
l.append(6)
l

[1, 2.4, 'Pranav', 6]

In [29]:
l.extend([3,5,8,9])
print(l)

[1, 2.4, 'Pranav', 6, 3, 5, 8, 9]


In [30]:
l=list(range(10))

In [31]:
l[1:5]

[1, 2, 3, 4]

In [32]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
l[0:10:3]

[0, 3, 6, 9]

In [37]:
my_dict = {"name": ['jim', 'pranav'], "age":[24, 23], "city": ['Chandigarh', 'Boston']}

In [38]:
display(my_dict)

{'name': ['jim', 'pranav'], 'age': [24, 23], 'city': ['Chandigarh', 'Boston']}

In [42]:
print(my_dict['name'][1])

pranav


In [43]:
l= [1,1,1,1,1,2,3,4,4,5,5,6,6,6]

In [44]:
set(l)

{1, 2, 3, 4, 5, 6}

In [45]:
x = set(l)
x.add(7)
x

{1, 2, 3, 4, 5, 6, 7}

In [46]:
tup = (1,2,3,4,5,6)

In [47]:
tup

(1, 2, 3, 4, 5, 6)

In [48]:
print(type(tup))

<class 'tuple'>


In [51]:
a = 21
b = 21
if a>b:
    print(True)
else:
    print(False)

False


In [65]:
for i in range(10):
    if i%2 == 0:
        print(f"{i} is even")
    else:
        print(f"{i} is odd")

0 is even
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [68]:
x = 0
while x<10:
    if x%2 == 0:
        print(f"{x} is even")
    else:
        print(f"{x} is odd")
    x+=1

0 is even
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [78]:
#list compherention
nouns = ['nick', 'vick', 'slick', 'trick', 'prick']
n = ["Example of a noun is :" + x for x in nouns]
print(n)

['Example of a noun is :nick', 'Example of a noun is :vick', 'Example of a noun is :slick', 'Example of a noun is :trick', 'Example of a noun is :prick']


In [83]:
try:
    x = 1/0
except ZeroDivisionError:
    print("divided by zero")
    print('executed when exception occurs')
else:
    print('no exception')
finally:
    print('final block')

divided by zero
executed when exception occurs
final block


In [84]:
try:
    x = 1/0
except ZeroDivisionError:
    print("divided by zero")
    print('executed when exception occurs')


divided by zero
executed when exception occurs


In [3]:
with open('myfirstfile.txt', 'a') as f:
    f.write("\n first line")
    f.write('\n aal is well')

In [4]:
with open('myfirstfile.txt', 'r') as f:
    for line in f:
        print(line)

first lineaal is well

 first line

 aal is well


In [6]:
f.close()

In [10]:
#functions

def divide_by_2(num):
    return num / 2

divide_by_2(10)

5.0

In [11]:
def db_columns(*args):
    for i in args:
        print(i)

db_columns('name', 'age', 'place')

name
age
place


In [19]:
def db_columns(**kwargs):
    for x in kwargs.items():
        print(x)

In [20]:
db_columns(name='Nav', height="6'2")

('name', 'Nav')
('height', "6'2")


In [35]:
square_lambda = lambda num: num**2
def sq(num): return num**2
square_lambda(5)

25

In [36]:
sq(6)

36

In [39]:
#object oriented programming
class example():
    pass

x = example()
print(type(x))

<class '__main__.example'>


In [43]:
class horse(object):
    def __init__(self,color):
        self.color=color
        print(color)

In [45]:
badal = horse(color="white")
badal.color

white


'white'

In [63]:
class circle(object):
    pi = 3.14
    
    def __init__(self, radius):
        self.radius = radius
        
    def calc_area(self):
        return self.radius**2 *circle.pi
    
    def set_radius(self, radius):
        self.radius = radius
    
    def get_radius(self):
        return self.radius

In [65]:
c = circle(5)
print('radius = ', c.get_radius())
print('area = ', c.calc_area())

radius =  5
area =  78.5


In [78]:
class student:
    school_name = 'CSU_Fresno'
    
    def __init__(self, name, age, major):
        self.name=name
        self.age=age
        self.major=major
        
    def get_info(self):
        print(self.name, self.age, self.major)
    
    @classmethod
    def change_school(cls, name):
        cls.school_name=name
    
    def get_notes(subjet_name):
        return ['ch 1', 'ch 2', 'ch 3']

In [79]:
Nav = student('Nav', 23, 'computer science')

In [80]:
Nav.name

'Nav'

In [81]:
Nav.major

'computer science'

In [82]:
Nav.school_name

'CSU_Fresno'

In [83]:
student.change_school('youtube university')

In [84]:
Nav.school_name

'youtube university'

In [1]:
#numpy
import numpy as np

In [2]:
my_list = [3,4,2,6,4]
np.array(my_list)

array([3, 4, 2, 6, 4])

In [3]:
two_d_list = [[1,2,3], [4,5,6], [7,8,9]]
np.array(two_d_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr = np.array(two_d_list)
print(arr.shape)
print(arr.dtype)

(3, 3)
int32


In [9]:
print(np.arange(0,10))
print(np.arange(0,20,2))
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.random.rand(3,3))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.23114104 0.27514187 0.0047608 ]
 [0.63149394 0.2516267  0.62903838]
 [0.98934095 0.37251909 0.04857289]]


In [10]:
#pandas
import pandas as pd

In [12]:
list1 = [1,1,1,2,3,4,5]
series = pd.Series(list1)
print(series)
print(series.index)
print(series.values)

0    1
1    1
2    1
3    2
4    3
5    4
6    5
dtype: int64
RangeIndex(start=0, stop=7, step=1)
[1 1 1 2 3 4 5]


In [15]:
idx = ['a','b','c']
arr=np.array([1,2,3])

pd.Series(data=arr, index = idx)


a    1
b    2
c    3
dtype: int32

In [18]:
df = pd.DataFrame([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(df)
print(df.index)
print(df.shape)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
RangeIndex(start=0, stop=3, step=1)
(3, 3)


In [19]:
df2 = pd.DataFrame([[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                 index = ['a','b','c'], columns=['x','y','z'])
df2

x  y  z
a  1  2  3
b  4  5  6
c  7  8  9